services:
  socks-proxy:
    image: vimagick/microsocks
    command: -p 1080

  server:
    build: .
    command: uv run python server.py
    environment:
      SERVER_BOT_TOKEN: ${SERVER_BOT_TOKEN}
      BASE_URL: "https://api.telegram.org/bot"
      UPSTREAM_HOST: "socks-proxy"
      UPSTREAM_PORT: "1080"
    depends_on:
      - socks-proxy

  client:
    build: .
    command: uv run python client.py
    ports:
      - "1080:1080"
    environment:
      CLIENT_BOT_TOKEN: ${CLIENT_BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      BASE_URL: "https://api.telegram.org/bot"
      LISTEN_HOST: "0.0.0.0"
      LISTEN_PORT: "1080"
    depends_on:
      - server
